# action.yml
name: 'Build Android'
description: 'A Github action to build the Pop Android family'
inputs:
  buildtargetname: # the PopSomething in /PopSomething.Android
    required: true
  buildpath: # path containing jni/android.mk
    required: true
  buildargs:
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.buildtargetname }}
    - ${{ inputs.buildpath }}
    - ${{ inputs.buildargs }}
