# action.yml
name: 'Build Android'
description: 'A Github action to build the Pop Android family'
inputs:
  buildscript:
    required: true
  buildpath:
    required: true
  buildargs:
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.buildscript }}
    - ${{ inputs.buildpath }}
    - ${{ inputs.buildargs }}
