# action.yml
name: 'Build Android'
description: 'A Github action to build the Pop Linux family'
inputs:
  project:  # project name
    required: true
  libdir:
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project }}
    - ${{ inputs.libdir }}
